export const defaultTags = [
    "groceries",
    "lunch",
    "dinner",
    "coffee",
    "bus",
    "uber",
    "spotify",
    "netflix",
    "gym",
    "doctor",
    "medicine",
    "gift",
    "birthday",
    "vacation",
    "kids",
    "pet",
    "school",
    "books",
    "clothes",
    "electronics",
    "rent",
    "insurance",
    "donation",
    "utilities",
    "internet",
    "phone"
];

export const categories = [
    "Food & Groceries",
    "Rent & Housing",
    "Utilities",
    "Transportation",
    "Entertainment",
    "Health & Insurance",
    "Subscriptions",
    "Education",
    "Shopping",
    "Travel",
    "Savings & Investments",
    "Gifts & Donations",
    "Childcare",
    "Pets",
    "Personal Care",
    "Taxes",
    "Miscellaneous"
];